# serverless.yml  ── capa Node 18 ─────────────────────────────────────────────
service: ${self:custom.base}-layer            # ej. mp-api-layer

frameworkVersion: '3'

custom:
  # ---------- parámetros genéricos ----------
  org:   ${opt:org,   'mp'}                   # organización
  app:   ${opt:app,   'api'}                  # aplicación
  stage: ${opt:stage, 'prod'}                 # dev | prod
  region:${opt:region,'us-east-1'}          # región AWS

  base:  ${self:custom.org}-${self:custom.app}  # mp-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ${self:custom.region}
  stage:  ${self:custom.stage}

layers:
  nodeModules:
    # Nombre visible en la consola:
    name: ${self:service}-${self:custom.stage}   # mp-api-layer-dev
    description: Dependencias Node.js compartidas
    compatibleRuntimes:
      - nodejs18.x
    path: aws-layer/nodejs    # aquí vive el node_modules
  
outputs:
  NodeModulesLambdaLayerQualifiedArn:
    description: ARN completo de la capa Node 18 con dependencias
    value:
      Ref: NodeModulesLambdaLayer
    export:
      Name: ${self:service}-${self:custom.stage}-NodeModulesLambdaLayerQualifiedArn

