service: siatech-kioscos-layer

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}

  # Bucket de despliegue estable
  deploymentBucket:
    name: siatech-layer-artifacts-${self:provider.stage}
    serverSideEncryption: AES256

layers:
  NodeModules:
    path: node-layer
    compatibleRuntimes: [nodejs18.x]
  PythonPackages:
    path: python-layer
    compatibleRuntimes: [python3.11]

# ── Recurso explícito para recrear el bucket si se borra ────────────
resources:
  Resources:
    DeploymentArtifactsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain            # nunca se destruye con el stack
      Properties:
        BucketName: siatech-layer-artifacts-${self:provider.stage}
        VersioningConfiguration: { Status: Enabled }
        PublicAccessBlockConfiguration:
          BlockPublicAcls:  true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
