service: siatech-kioscos-layer
frameworkVersion: '^3.40.0'

provider:
  name: aws
  region: us-east-2
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}

layers:
  NodeModules:
    path: node-layer          # Serverless buscará node-layer/nodejs/**
    compatibleRuntimes: [nodejs18.x]
  PythonPackages:
    path: python-layer        # Serverless buscará python-layer/python/**
    compatibleRuntimes: [python3.11]

resources:
  Resources:
    DeploymentArtifactsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: siatech-layer-artifacts-${self:provider.stage}

        VersioningConfiguration: { Status: Enabled }
        PublicAccessBlockConfiguration:
          BlockPublicAcls:  true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
